version: '3'
services:
    php:
        build: .
#        command: tail -f /dev/null
        # permissions of current, same in Dockerfile
        user: 1000:1000
        volumes:
            - .:/var/www/html
